project:
  type: book
  output-dir: docs

book:
  title: "Cardiology Notes"
  author: "Mirza S. Khan"
  date: "7/28/2022"
  chapters:
    - index.qmd
    - part: "Hospital & EMR Info"
      chapters: 
        - inhouse-shifts.qmd
    - part: "Numbers & Metrics"
      chapters:
        - pulse-pressure.qmd
    - part: "Cardiology Fundamentals"
      chapters:
        - hypertension.qmd
        - orthostatic-hypotension.qmd
        - primary-prevention.qmd
        - cad.qmd
        - cholesterol.qmd
        - t2dm.qmd
        - stress-tests.qmd
        - troponinemia.qmd
        - syncope.qmd
        - heart-monitors.qmd
        - pulmonary-htn.qmd
        - smoking-cessation.qmd
        - weight-loss.qmd
    - part: "Physical Exam"
      chapters: 
        - jvp.qmd
    - part: "Chest Pain & ACS"
      chapters:
        - chest-pain.qmd
        - acs.qmd
        - sgarbossa-criteria.qmd
        - minoca.qmd
        - pericarditis.qmd
        - pulmonary-embolism.qmd
        - prinzmetal.qmd
    - part: "Heart Failure"
      chapters:
        - heart-failure.qmd
        - icd-hf.qmd
        - crt-hf.qmd
        - hocm.qmd
    - part: "Rhythm"
      chapters: 
        - bradycardia.qmd
        - afib.qmd
        - wpw.qmd
        - complete-heart-block.qmd
        - pvc.qmd
        - supraventricular-tachy.qmd
        - ventricular-tachy.qmd
        - qt-prolong.qmd
    - part: "Valvular disorders"
      chapters: 
        - pad.qmd
        - aortic-stenosis.qmd
        - prosthetic-valves.qmd
    - part: "Vascular disorders"
      chapters: 
        - carotid-artery-stenosis.qmd
        - renal-artery-stenosis.qmd
    - part: "CICU"
      chapters:
        - cardiogenic-shock.qmd
        - post-cardiacarrest.qmd
        - mcs.qmd
        - iabp.qmd
        - impella.qmd
        - constrictive-pericarditis.qmd
    - part: "Emergencies"
      chapters: 
        - acls.qmd
        - mi-complications.qmd
        - pericardial-effusion.qmd
        - tamponade.qmd
        - hypertensive-crises.qmd
    - part: "Cardio-Obstetrics"
    - part: "ECG"
      chapters: 
        - ecg-approach.qmd
        - bbb.qmd
        - fascicular-blocks.qmd
        - brugada-syndrome.qmd
        - st-elevation.qmd
    - part: "Waveforms"
      chapters:
        - ra-waveform.qmd
    - part: "Pharmacology"
      chapters:
        - aspirin.qmd
        - p2y12.qmd
        - statins.qmd
        - antiHTN.qmd
        - thiazides.qmd
        - entresto.qmd
        - steroids.qmd
        - immunosuppressants.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib
pdf-engine: xelatex
filters: 
  - lightbox
lightbox: auto
format:
  html:
    theme:
      light: flatly
      dark: darkly
    code-copy: true
  # pdf:
  #   documentclass: scrbook
  #   include-in-header: 
  #     text: |
  #       \usepackage{enumitem}
  #       \setlistdepth{9}
  #       \setlist[itemize,1]{label=\textbullet}
  #       \setlist[itemize,2]{label=\textbullet}
  #       \setlist[itemize,3]{label=\textbullet}
  #       \setlist[itemize,4]{label=\textbullet}
  #       \setlist[itemize,5]{label=\textbullet}
  #       \setlist[itemize,6]{label=\textbullet}
  #       \setlist[itemize,7]{label=\textbullet}
  #       \setlist[itemize,8]{label=\textbullet}
  #       \setlist[itemize,9]{label=\textbullet}
  #       \renewlist{itemize}{itemize}{9}



