project:
  type: book

book:
  title: "cards-notes"
  author: "Mirza S. Khan"
  date: "7/28/2022"
  chapters:
    - index.qmd
    - part: "Numbers & Metrics"
      chapters:
        - pulse-pressure.qmd
    - part: "Cardiology Fundamentals"
      chapters:
        - hypertension.qmd
        - cad.qmd
        - cholesterol.qmd
        - stress-tests.qmd
        - troponinemia.qmd
    - part: "Chest Pain & ACS"
      chapters:
        - chest-pain.qmd
        - acs.qmd
        - minoca.qmd
        - prinzmetal.qmd
    - part: "Heart Failure"
      chapters:
        - heart-failure.qmd
        - icd-hf.qmd
        - crt-hf.qmd
    - part: "Rhythm"
      chapters: 
        - afib.qmd
        - supraventricular-tachy.qmd
        - ventricular-tachy.qmd
    - part: "CICU"
      chapters:
        - cardiogenic-shock.qmd
    - part: "Emergencies"
      chapters: 
        - acls.qmd
        - mi-complications.qmd
        - tamponade.qmd
    - part: "ECG"
    - part: "Waveforms"
      chapters:
        - ra-waveform.qmd
    - part: "Pharmacology"
      chapters:
        - antiHTN.qmd
        - entresto.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-copy: true
  pdf:
    documentclass: scrreprt



