# Advanced Cardiovascular Life Support (ACLS)

::: callout-note
If *no* advanced airway, the ratio of compressions to ventilation (breaths) is **30:2**
:::

## Tachycardia with pulse

-   If *sustained* VTach with a pulse *and* HD unstable → DC synchronized cardioversion
-   If *sustained* VTach with a pulse *and* HD stable → amiodarone (See \@ref(stable-vt-vf))
-   Regular narrow QRS complex and suspect supraventricular tachycardia (\@ref(supraventricular-tachycardia-svt))
    -   IV adenosine
        -   First dose: 6 mg rapid IV push
        -   Second dose (if needed): 12 mg (up to 2x)

## Pulseless Tachycardia

::: callout-caution
## Pulseless VTach and hypOtensive VTach are treated like VFib
:::

-   If VFib or pulseless VTach → DC [**un**]{.underline}synchronized cardioversion

## Bradycardia with pulse

-   First line: atropine
-   If atropine is ineffective:
    -   transcutaneous pacing
    -   dopamine infusion
    -   epinephrine infusion
-   Acute sinus bradycardia in the setting of an acute MI is usually temporary so atropine alone may be sufficient
