# Bradycardia

## Note

``` text
# Bradycardia
- Defined as non-physiologic sinus rate of less than 50 bpm and/or sinus pauses of >3 s (2018 Guidelines)
- Symptomatic?
  - If not, no increased risk for incident CVD/mortality (Dharod et al., 2016); no need for further Tx or ppm
  - If Sx, risk for syncope, incident AFib, and HF -> if chronic Sx sinus node dysfunction, will need ppm
    - Atropine: first dose is 0.5 mg bolus; can repeat q3-5 mins (max = 3g, i.e. 6x)
- History and evaluation to identify potential reversible causes
- Medication review: ***
- 12-lead ECG
  - look for structural heart dz, conduction disturbance (e.g. AV block), etc.
  - Development of LBBB is assoc w/ structural heart disease and ↑ mortality
- Echo
  - Class I rec if new LBBB, Mobitz Type II AV block, high grade AV block or complete AV block
- If HD unstable or risk of asystole -> temporary pacing may be needed
- Consider ambulatory ECG monitoring to establish Dx or identify Sx-rhythm correlation
- Consider exercise testing if Sx are temporally related to exercise, ASx 2nd degree AV block, or suspected chronotropic incompetence
- Treat/Evaluate for sleep-disordered breathing
  - Class I rec if nocturnal bradycardia and documented/suspected sleep-disordered breathing
  - Tx of sleep apnea can result in 90% reduction in bradycardia events (Becker et al., 1995)
- Labs:
  - TSH w/ reflex
  - CMP
  - Lyme titers
- Defer genetic testing at this time as yield likely to be low
  - If suspected inherited condition, can consider w/ assistance of genetic counselor
```

-   See different types of heart monitors in @sec-heartmonitors.

-   Check for end-organ perfusion

-   BP - check for hypOtension, HD instability

-   QRS

    -   if wide, suggests *escape* rhythm (bad!)
        -   May need to get the dopamine going and begin coordinating for pacing
    -   if narrow, good (relatively)

-   Syncope - bad if present

## Overnight Treatment Options

-   Atropine
    -   unlikely to be successful if block below AV node
    -   rarely useful in complete heart block
-   Transcutaneous pacing
    -   temporary measure
    -   uncomfortable for patient
    -   can be used transiently if HD unstable
-   Chronotropic medications, e.g. dopamine, dobutamine, and isoproterenol
-   Transvenous pacing

## Temporary transvenous pacemaker

1\. Venous access

2\. Setting up your generator

3\. Floating the pacer wire

4\. Ensure pacemaker capture and adjustment

    1. Rate: usually 20 above intrinsic (80 bpm)

    2. Output: once ECG capture, decrease mA to find minimum threshold for capture, then increase 2-3 times that

    3. Sensitivity (mV): the higher the sensitivity, the lower threshold to pick up intrinsic rhythm. Usually decrease to half of the sensitvity threshold.

Instructions and details on bedside placemet at [Taming the SRU](https://www.tamingthesru.com/transvenous-pacemaker)

## Symptoms

-   Common symptoms of bradycardia include syncope, presyncope, transient dizziness or lightheadedness, fatigue, dyspnea on exertion, heart failure symptoms, or confusion resulting from cerebral hypoperfusion. [@sidhu2020]

## Causes

-   Sinus brady occurs in 15-25% of pts w/ acute MI (See @sec-acs), particular if it involves the RCA because it supplies the SA node in \~60% of folks.

+--------------------------------------------+-----------------------------------------------------------+
| General cause                              | Conditions                                                |
+============================================+===========================================================+
| **Autonomic dysfunction**                  | -   Carotid sinus hypersensitivity                        |
|                                            | -   Neurally-mediated syncope                             |
|                                            | -   Situational syncope                                   |
+--------------------------------------------+-----------------------------------------------------------+
| **Cardiomyopathy**                         | -   Ischemic                                              |
|                                            |                                                           |
|                                            | -   Non-ischemic                                          |
|                                            |                                                           |
|                                            | -   Infiltrative                                          |
+--------------------------------------------+-----------------------------------------------------------+
| **Congenital ❤️ disease** \| \| \|         |                                                           |
+--------------------------------------------+-----------------------------------------------------------+
| **Degenerative**                           |                                                           |
+--------------------------------------------+-----------------------------------------------------------+
| **Infection**                              | -   Lyme disease                                          |
|                                            |                                                           |
|                                            | -   Infective endocarditis                                |
|                                            |                                                           |
|                                            | -   Chagas disease                                        |
+--------------------------------------------+-----------------------------------------------------------+
| **Ischemia/Infarction - esp. inferior MI** |                                                           |
+--------------------------------------------+-----------------------------------------------------------+
| **Meds/Drugs**                             | -   anti-HTN: BBs, verapamil, diltiazem                   |
|                                            |                                                           |
|                                            | -   anti-arrhythmics: amio, dronedarone, sotalol, digoxin |
|                                            |                                                           |
|                                            | -   psychoactive: phenothiazines, opioids, TCAs           |
+--------------------------------------------+-----------------------------------------------------------+
| **Metabolic/Endocrine**                    | -   Acidosis                                              |
|                                            |                                                           |
|                                            | -   hypO- or hyperK                                       |
|                                            |                                                           |
|                                            | -   hypOthyroid, hypOadrenal state                        |
|                                            |                                                           |
|                                            | -   hypOthermia                                           |
|                                            |                                                           |
|                                            | -   hypOxia                                               |
+--------------------------------------------+-----------------------------------------------------------+
| **Rheumatologic**                          | -   RA                                                    |
|                                            |                                                           |
|                                            | -   Scleroderma                                           |
|                                            |                                                           |
|                                            | -   SLE                                                   |
+--------------------------------------------+-----------------------------------------------------------+
| **Surgical/traumatic**                     | -   Catheter ablation                                     |
|                                            |                                                           |
|                                            | -   Surgical correction of congenital **❤️** dz           |
|                                            |                                                           |
|                                            | -   Valve surgery                                         |
|                                            |                                                           |
|                                            | -   Septal myectomy/Alcohol septal ablation               |
+--------------------------------------------+-----------------------------------------------------------+

: Conditions associated with bradycardia and conduction disorders. (Sidhu & Marine, 2020)

### Drugs associated with Bradycardia

-   Very comprehensive list of Drug-Induced Arrhythmias (AHA Scientific Statement) [@tisdale2020]

+--------------------------------------------+-----------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| Drug Class                                 | Drug(s)                                                                                                   | MOA                                                                                                                |
+============================================+===========================================================================================================+====================================================================================================================+
| Acetylcholinesterase Inhibitor             | Donepezil, Neostigmine, Physostigmine, Pyridostigmine                                                     | Stimulation of activity of the parasympathetic nervous system, leading to inhibition of automaticity of sinus node |
+--------------------------------------------+-----------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| Anesthetic                                 | Bupivacaine, Propofol                                                                                     | Reduction in sympathetic activity                                                                                  |
+--------------------------------------------+-----------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| Antiarrhythmic                             | Adenosine, Amiodarone, Disopyramide, Dronedarone, Flecainide, Ivabradine, Propafenone, Quinidine, Sotalol | Node inhibition                                                                                                    |
+--------------------------------------------+-----------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| Anticancer                                 | Thalidomide                                                                                               |                                                                                                                    |
+--------------------------------------------+-----------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| Antidepressant                             | Citalopram, Escitalopram, Fluoxetine                                                                      | Na^+^ and Ca^2+^ inhibition                                                                                        |
+--------------------------------------------+-----------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| Antihypertensive                           | Clonidine, β-Blockers (including eye drops), Diltiazem, Verapamil                                         | Clonidine: Stimulation of central α~2~-receptors, reducing release of norepinephrine\                              |
|                                            |                                                                                                           | \                                                                                                                  |
|                                            |                                                                                                           | β-Blockers and non-DHP CCBs: inhibition of automaticity of sinus node                                              |
+--------------------------------------------+-----------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| Inotrope                                   | Digoxin                                                                                                   | ↑ vagal tone                                                                                                       |
+--------------------------------------------+-----------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| Sphingosine 1-phosphate receptor modulator | Fingolimod                                                                                                | Modulation of the sphingosine 1-phosphate receptors                                                                |
+--------------------------------------------+-----------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+
| Vasodilator/antiplatelet                   | Dipyridamole                                                                                              | Increased adenosine leading to direct sinoatrial/atrioventricular node inhibition                                  |
+--------------------------------------------+-----------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+

: Drugs that may cause/exacerbate Sinus Bradycardia/AV Block

## Pharmacotherapy

| Medication                                       | Utility                                                                                                                                                 |
|--------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------|
| Atropine                                         | A parasympatholytic drug that can affect sinoatrial conduction, sinus node automaticity, and AV conduction.                                             |
| Isoprotenerol, Dopamine, Dobutamine, Epinephrine | Direct stimulation of beta-receptors to increase sinus node automaticity and AV conduction. Should use with caution if concerned for coronary ischemia. |
| Intravenous calcium                              | Can be used if bradycardia is attributed to calcium channel blocker overdose.                                                                           |
| Glucagon                                         | Can be used if bradycardia is attributed to calcium channel blocker or beta-blocker overdose. May cause nausea and vomiting.                            |
| High dose insulin                                | Can be used if bradycardia is attributed to calcium channel blocker or beta-blocker overdose. Risk of hypoglycemia.                                     |
| Aminophylline                                    | Can be used in heart transplant patients, spinal cord injury, or inferior MI with AV block.                                                             |

: Medications to treat bradycardia (Sidhu & Marine, 2020)
