# Cardiogenic Shock {#sec-cardiogenicshock}

-   cool extremities

-   *narrow* pulse pressure (See @sec-pulsepressure)

-   labored breathing

-   Cheyne-Stokes respiration

-   abdominal bloating/nausea

-   End-organ dysfunction: oliguria, AMS, etc.

-   Phenotypes

    -   ACS-related cardiogenic shock
    -   acute-on-chronic heart failure related cardiogenic shock

## Etiologies of CS

| General Cause                      | Specific Etiologies                                                                                                                                                                                                                 |     |     |     |
|-------|----------------------------------------------|-------|-------|-------|
| Ischemic                           | Acute myocardial infarction<br>Unstable angina with global ischemia<br>Right ventricular infarction<br>Complications of ischemic heart disease<br>Papillary muscle rupture<br>Acute ventricular septal defect<br>Myocardial rupture |     |     |     |
| Valvular                           | Severe aortic stenosis or insufficiency<br>Severe mitral regurgitation or stenosis<br>Severe pulmonic stenosis or regurgitation<br>Severe tricuspid regurgitation or stenosis                                                       |     |     |     |
| Myocardial disease/unknown         | Acute myocarditis<br>Giant cell myocarditis<br>Takotsubo stress myocarditis<br>Substance abuse<br>Toxins<br>Chemotherapeutic agents<br>End-stage ischemic or nonischemic cardiomyopathy                                             |     |     |     |
| Extracardiac                       | Cardiac tamponade<br>Acute aortic dissection with aortic insufficiency, tamponade, or rupture<br>Large pulmonary embolism                                                                                                           |     |     |     |
| End-stage congenital heart disease |                                                                                                                                                                                                                                     |     |     |     |
