# Cholesterol Management

TODO


-   **ASCVD Risk Categories** for *primary prevention*
    -   Low risk: \< 5%
    -   Borderline risk: 5-7.5%
    -   Intermediate risk: 7.5-19.9%
    -   High risk: â‰¥ 20%
-   Recommendations generally refer to patients ages 40-75 years old. Evidence is now showing improved CV mortality and fewer ASCVD events in adults aged â‰¥ 75 yo w/o hx of baseline ASCVD taking statins (compared to non-statin users) in the VA population [@orkaby2020].
-   What are the "high risk" ASCVD groups?
    -   Acute coronary syndrome (ACS) in the last 12 monthsÂ 
    -   Multiple heart attacks
    -   Ischemic stroke
    -   Symptomatic peripheral artery disease (claudication with ABI \< 0.85, or previous revascularization or amputation)Â 
    -   Age \> 65 years
    -   Heterozygous familial hypercholesterolemia
    -   Prior coronary bypass surgery or PCI outside of the above events
    -   Diabetes mellitus
    -   Hypertension
    -   Chronic kidney disease
    -   Current smoker
    -   Persistently elevated LDL \> 100 mg/dL despite max statin therapy and ezetimibe
    -   Congestive heart failure
-   Pts with established CAD, but do not meet any 'high risk' criteria are considered **Stable ASCVD**
    -   Recommendations for Stable ASCVD:
        -   \< 75 yo â†’ high-intensity statin (Goal LDL \< 70 mg/dL)
        -   75+ yo â†’ high/moderate-intensity statin
-   Risk enhancing ASCVD factors should be considered to guide mgmt b/w borderline and intermediate risk groups [@grundy2019]
    -   family history of premature CAD (â™‚ \< 55 yo; â™€ \< 65 yo)
    -   primary hypercholesterolemia w/ LDL 160-189 mg/dL
    -   metabolic syndrome
    -   CKD
    -   chronic inflammatory disorders (e.g. RA, HIV/AIDS)
    -   premature menopause (menopause \< 40 yo)
    -   pregnancy-related adverse outcomes (e.g. pre-eclampsia)
    -   non-fasting triglycerides \> 175 mg/dL on *at least* 3 occasions
    -   high-risk ethnicities (e.g. South Asians)
    -   Other labs:
        -   hs-CRP \> 2 mg/dL
        -   Lp(a) \> 50 mg/dL
        -   apoB \> 130 mg/dL
    -   Ankle-brachial index (ABI) \< 0.9
-   Coronary artery calcium (CAC) scoring may also be useful to guide management in unclear settings or when a pt is straddling b/w borderline/intermediate risk groups (especially if pt is reluctant to start a statin)
    -   According to the MESA study, diabetics with a CAC score of zero had similar event rate as those without diabetes [@bertoni2016].

-   Statin flavors:

    -   High-intensity

        -   Atorvastatin 40-80

        -   Rosuvastatin 20-40

    -   Moderate-intensity

        -   Atorvastatin 10-20

        -   Rosuvastatin 5-10

        -   Simvastatin 20-40

        -   Pravastatin 40-80

-   LDL reduction goals on statin therapy

    -   High-intensity: â†“ in LDL by \> 50%

    -   Moderate-intensity: â†“ in LDL by 30-49%

    -   Low-intensity: â†“ in LDL by \< 30%

-   **Follow-up**

    -   Repeat LDL 4-12 wks after initiation

    -   Subsequent f/u: repeat LDL after 3-13 months (depending on the pt)

        -   stable: check annually or even every 4-6 years in younger pts

-   Who *always* is indicated to receive a statin?

    -   DM + age \> 40 yo

    -   Primary hypercholesterolemia (LDL â‰¥ 190)

-   **Secondary prevention**

    -   High-intensity statin (unless \> 75 yo, where recommended to start high/moderate-intensity statin)

    -   If LDL goal is *not met*:

        -   add ezetimibe (Zetia) (IMPROVE-IT trial)

        -   if still not at goal â†’ add PCSK9 inhibitor (ODYSSEY and FOURIER trials)

-   Lifestyle modifications

    -   Diet

        -   ðŸ˜‹ Enjoy rich in fruits, veggies, polyunsaturated fats, lean meats, plant-based proteins, phytosterols and fiber

        -   âš ï¸ Avoid saturated fats, refined carbs/sweets and red meat

    -   Exercise

        -   Moderate/vigorous intensity aerobic exercise 3-4x/wk for 40 mins each session

+------------------------------------------+-------------------------+----------------------------------------------------+
| Indication                               | Statin Intensity        | Rx if not at LDL goal                              |
+==========================================+=========================+====================================================+
| Multiple major ASCVD events *or\         | High                    | High-intensity: Aim for â‰¥ 50% â†“ in LDL\            |
| *Major ASCVD event + multiple high RFs   |                         | If LDL â‰¥ 70 (or non-HDL â‰¥ 100): ezetimibe Â± PCSK9i |
+------------------------------------------+-------------------------+----------------------------------------------------+
| LDL â‰¥ 190 mg/dL                          | High                    | High-intensity: Aim for â‰¥ 50% â†“ in LDL\            |
|                                          |                         | If LDL â‰¥ 100: ezetimibe Â± PCSK9i                   |
+------------------------------------------+-------------------------+----------------------------------------------------+
| High-risk: ASCVD â‰¥ 20%                   | High                    | High-intensity: Aim for â‰¥ 50% â†“ in LDL\            |
|                                          |                         | If LDL â‰¥ 70: ezetimibe Â± PCSK9i                    |
+------------------------------------------+-------------------------+----------------------------------------------------+
| Stable ASCVD: Clinical ASCVD w/o high RF | High/Moderate           | High-intensity: Aim for â‰¥ 50% â†“ in LDL\            |
|                                          |                         | Mod-intensity: Aim for 30-49% â†“ in LDL\            |
|                                          |                         | If LDL â‰¥ 70: ezetimibe Â± PCSK9i                    |
+------------------------------------------+-------------------------+----------------------------------------------------+
| DM                                       | High/Moderate\          | High-intensity: Aim for â‰¥ 50% â†“ in LDL\            |
|                                          | High if multiple RFs    | Mod-intensity: Aim for 30-49% â†“ in LDL             |
+------------------------------------------+-------------------------+----------------------------------------------------+
| Intermediate risk: ASCVD 7.5-20%         | Moderate                | Mod-intensity: Aim for 30-49% â†“ in LDL             |
+------------------------------------------+-------------------------+----------------------------------------------------+
| Low/Borderline-risk: ASCVD â‰¤ 7.5%        | Shared decision making\ |                                                    |
|                                          | Consider risk enhancers |                                                    |
+------------------------------------------+-------------------------+----------------------------------------------------+

: Lipid Management ([Curbsiders, Ep. 191](https://thecurbsiders.com/podcast/191-lipids))

-   Clinical features of *severe* hyperlipidemia

    -   Xanthelasma

        -   yellow plaques on eyelids

    -   Xanthoma

        -   hard, yellow masses typically found on tendons (finger extensors, Achilles, plantar tendons)

    -   Pancreatitis - if *severe* hypertriglyceridemia

## Hypertriglyceridemia

-   First-line: lifestyle modification

-   If TG persistently \> 500 mg/dL â†’ next step is to start a statin

-   If TG \> 1,000 mg/dL â†’ start a fibrate (to avoid pancreatitis)

-   Icosapent ethyl (REDUCE-IT trial) [@bhatt2019]

    -   not the same thing as fish oil

    -   can be added to pts with â†‘ TG despite being on statins, i.e. add as an adjunct to statins

        -   â†‘ TG defined in REDUCE-IT trial: TG level of 135-499 mg/dL

    -   Dose from REDUCE-IT trial: 2 g of icosapent ethyl BID

## O'Keefe Lecture Notes

### Statins
- Dr. O'Keefe is not a fan of Atorva 80 mg b/c side effects of statins are dose-dependent.
	- You can get rhabdo with high doses of statins. Dr. O'Keefe gave an example of post-transplant patient on Atorva 80 who got rhabdo and died a few months later.
	- Delta between 40 mg and 80 mg of atorva is 48% â†’ 51% reduction (delta is only 3%)
- Atorva is the ðŸŒŸ
- Rule of thumb: 6% reduction when doubling a statin dose. Better off adding ezetimibe: zetio on its own 16% reduction, zetia + statin (synergistic effect): 25% reduction.
- Newborn baby LDL is 25-30 mg/dL. Hunter/gatherers have also been studied and have like 40-50 mg/dL.
	- You don't want a 0 LDL! Cholesterol is an important molecule, so you need some.
- Dr. O'Keefe gets nervous getting someones LDL < 30
- Side effects are not related to LDL level, rather related to statin dose.
- Mnemonic for statin side effects "LIPITOR":
	- Liver effects
	- Increased blood sugar
	- Pain (muscles)
	- Impaired memory
	- Tiredness/Fatigue
	- Other (headaches)
	- Rhabdomyolysis
- SAMSON trial (BMJ, 2021)
	- 200 statin intolerant patients; "n-of-1" experiments
	- Compared atorva 20 mg vs placebo
	- Intolerable muscle sx: 9% in statin group discontinued, 7% discontinued placebo
- Dr. O'Keefe: "when I start someone on a statin, I also start them on **CoQ10**."
	- If patient c/o myalgias, he'll increase the dose of **CoQ10**

- Pitavastatin
	- a "cool" statin
	- Not as strong as atorva
	- 4 mg dose $\approx$ 20 mg of atorva
	- Unlike atorva, rosuva, simva, Pitavastatin less likely to induce DM in patients. If anything pitava can lower A1c by 0.1%

### Ezetimibe
- Dr O'Keefe loves ezetimibe
- EWTOPIA75 study out of Japan: zetia monotherapy vs control
- IMPROVE-IT trial
	- compared to folks on simva vs simva +zetia: combo further reduced cardiovascular events

### PCSK9 inhibitors
- Evolocumab â†’ reduction of MACE
- Injection once every 2 weeks
- Alirocumab and Lp(a)
- Statins, exercise, diet don't do anything to effect Lp(a)
- Don't do anything for TG or HDL, purely work on LDL

### Omega-3
- REDUCE-IT trial â†’ â†“ MACE 26%
	- icosapent ethyl (Vascepa) vs placebo
- You want to get TG < 150
- Dr O'Keefe: everybody should be on 1g of EPA+DHA
	- If strong indications (hyperTG, atherosclerosis) at least 2g
	- In certain patients, up to 4g/day
- May increase risk of AFib (dose-dependent)
	- Omega-3 is correlated with â†‘ vagal effect (â†“ HR, etc.), but there is a subset that increased risk of brady, APC â†’ â†‘ risk of AFib
- Bill Harris is aka "The Codfather" ðŸ˜†

### Fibrates
- Fenofibrates are really the only ones we use. We often use it with a statin.
- It's 3rd line for hyperTG
	- First line is statin, second line is Omega-3
- Recall, goal is to get TG < 150
- Low glycemic diet, eliminating added sugars will lower TG dramatically

### Niacin
- Dr. O'Keefe is not a fan. If someone shows up on it, he'll take them off of it.