# Constrictive Pericarditis

## Echo Findings

### Septal Bounce

<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">1⃣ SEPTAL BOUNCE<br>Paradoxical bouncing motion of IVS in early diastole, at the beginning directed towards LV and then away from LV ➡️ Sign of increased ventricular interdipendence <a href="https://t.co/mWx2jwfLWl">pic.twitter.com/mWx2jwfLWl</a></p>&mdash; Corrado Fiore MD, FEACVI (@fiore_corrado) <a href="https://twitter.com/fiore_corrado/status/1551495278976552962?ref_src=twsrc%5Etfw">July 25, 2022</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 

### E/A variation at level of MV inflow

<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">2⃣ E/A variation at the level of MV inflow.<br>Respiratory variation of peak E wave velocity should be at least &gt;15%.<br>Inspiratory decrease and expiratory increase of E wave vel. (not so prominent here) <a href="https://t.co/LcNfgzG0oN">pic.twitter.com/LcNfgzG0oN</a></p>&mdash; Corrado Fiore MD, FEACVI (@fiore_corrado) <a href="https://twitter.com/fiore_corrado/status/1551495284521410560?ref_src=twsrc%5Etfw">July 25, 2022</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 

### Annulus Reversus

<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">3⃣ ANNULUS REVERSUS<br>Increased early relaxation velocity (e&#39;), with medial velocity greater than lateral <a href="https://t.co/oBVi99bl3V">pic.twitter.com/oBVi99bl3V</a></p>&mdash; Corrado Fiore MD, FEACVI (@fiore_corrado) <a href="https://twitter.com/fiore_corrado/status/1551495289541988353?ref_src=twsrc%5Etfw">July 25, 2022</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 

### Diastolic Flow Reveral in Expiration

<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">4⃣ DIASTOLIC FLOW REVERSAL IN EXPIRATION<br>Always look for this sign with PW whitin hepatic vein.<br><br>PS (i apologize for EKG and respirometric traces, but i don &#39;t why in my original clips i can see them and here not) <a href="https://t.co/BnPXbV1f3x">pic.twitter.com/BnPXbV1f3x</a></p>&mdash; Corrado Fiore MD, FEACVI (@fiore_corrado) <a href="https://twitter.com/fiore_corrado/status/1551495295451758592?ref_src=twsrc%5Etfw">July 25, 2022</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 