# Approach to reading ECGs

-   Rate
-   Rhythm
-   Axis
-   Hypertrophy
-   Interval
-   Signs of ischemia
    -   Q waves
    -   Inverted T waves
    -   ST segment elevation/depression

## Rate

-   Horizontal
    -   Small box: 0.04s
    -   Large box: 0.2s
-   Vertical
    -   Small box: 0.1 mV (1mm)
    -   Large box: 0.5 mV (5mm)
-   300, 150, 100, 75, 60, 50
    -   large boxes divided by 300 â†’ HR
-   For *slow* HR:
    -   count the number of QRS complexes in a 10 second strip
    -   multiply this number by **6**

## Rhythm

-   Normal sinus rhythm:
    -   "a P for every QRS and a QRS for every P"
    -   aVR: ðŸ‘‡ deflection
    -   II: â˜ï¸ deflection

## Axis

The term axis refers to the direction of the mean electrical vector, representing the average direction of current flow. **It is defined in the frontal plane only**. The concept of axis deviation is most successfully applied to ventricular hypertrophy.[@thaler2018]

-   Look at leads I and aVF
    -   â˜ï¸â˜ï¸ â†’ normal axis
    -   â˜ï¸ðŸ‘‡ â†’ LAD
        -   EXCEPTION: if lead II is positive, then *normal* axis
    -   ðŸ‘‡â˜ï¸ â†’ RAD
    -   ðŸ‘‡ðŸ‘‡ â†’ eRAD
-   Left axis deviation - â˜ï¸ðŸ‘‡
    -   Upright (positive) in lead I + Downright (negative) in lead aVF
    -   Look at lead II
        -   if uprightÂ â†’ normal (0 to -30Ëš)
        -   if negativeÂ â†’ LAD (-30Ëšto -90Ëš)
-   If LAD present, look for LAFB
-   If RAD present, look for LPFB

## Hypertrophy

Hypertrophied myocardium demands more blood supply for the overgrown heart muscle, but it has a reduced density of capillaries and is therefore more susceptible to ischemia than is normal myocardium. [@thaler2018]

- Left ventricular hypertrophy (LVH)
  - Limb leads: will commonly find left axis deviation (LAD)
  - **R wave in V~5~-V~6~Â (tallest) + S wave in V~1~-V~2~Â \> 35 mm**
    - most specific, but not the most sensitive
  - R wave in lead I + S wave in lead III \> 25 mm
  - R wave in lead V5 > 26 mm
  - R wave in lead V6 > 20 mm
  - R wave amplitude in lead V6 exceeds the R-wave amplitude in lead V5
  - Cornell Criteria: R wave in aVL + S wave in V3 > 28 mm in men or > 20 mm in women
    - considered to be the most accurate
- Right ventricular hypertrophy (RVH)
  - Limb leads: will commonly find right axis deviation (RAD); mean axis > 100Ëš
  - Two commonly used criteria:
    - R wave in V~1~Â â‰¥ 7 mm
    - R/S wave ratio in V~1~Â \> 1
  - MCC are pulmonary disease and congenital heart disease

Findings of ventricular hypertrophy may also be associated with **secondary repolarization abnormalities**, e.g. downsloping ST-segment depression and T wave inversion. If present, right ventricular repolarization abnormalities will be seen in leads V1 and V2, and left ventricular repolarization abnormalities will be most evident in leads I, aVL, V5, and V6. [@thaler2018]

:::{.callout-tip}
The normal P wave is less than 0.12 second in duration, and the largest deflection, that is, voltage, whether positive or negative, should not exceed 2.5 mm.[@thaler2018]
:::

- Left atrial enlargement (LAE; _P mitrale_)
  - the terminal (left atrial) portion of the P wave >1 mm below the isoelectric line in lead V1 **and**
  - the terminal portion of the P wave should be at least 1 small block (0.04 second) in width
  - No significant axis deviation is seen because the left atrium is normally electrically dominant.
- Right atrial enlargement (RAE; _P pulmonale_)
  - P waves with an amplitude >2.5 mm in at least one of the inferior (leads II, III, and aVF)
  - P wave with an amplitude >1.5 mm in V1, V2
  - width of P wave often _unchanged_
  - Possible right axis deviation of the P wave

## Intervals

- PR interval
    - normal: 120-200
- QRS interval
    - normal: \<100
    - "wide" if \>120 (3 small boxes)
- QT interval
    - normal: \<440 in â™‚, \<460 in â™€
    
## Signs of Ischemia

- hyperacute T-waves
    - hill-like (*not* peaked)
- T-wave inversion
    - deep and symmetric
- ST-elevation
- Q waves

:::{.callout-warning}
**Posterior STEMI** will show ST depression in the anterior precordial leads (V~1~ to V~3~) + R/S ratio \> 1 + *upright* T-waves. Get a posterior EKG by throwing V4-V6 leads on the patient's back beneath their left scapula. Posterior STEMI if posterior EKG leads showing ST elevation \> 0.5mm
:::

## ECG Anatomic Distributions

| **Distribution** | **Coronary a.** | **Leads**      | **Reciprocal Changes** |
|------------------|-----------------|----------------|------------------------|
| Inferior         | RCA, PDA        | II, III, aVF   | anterior, lateral      |
| Lateral          | LCx             | I, aVL, V5, V6 | inferior               |
| Anterior         | LAD             | V1-V6          | inferior               |
| Posterior        | RCA             | posterior      | anterior (esp. V1)     |