# Sacubitril/Valsartan {#sec-entresto}

-   PARADIGM-HF trial: ARNI 20% RR reduction vs ACEi trial was stopped early due to effect.

    -   There are some valid concerns in how the trial was conducted. These concerns may influence why uptake of this med has been slow. [@Ahn2018]
    -   Valsartan (of Entresto) was max dose, but Enalapril was not.
    -   There was a longer run-in for Entresto compared to Enalapril, which may bias towards Entresto.

-   PARAGON-HF trial: Entresto vs. valsartan in HF with LVEF ≥ 45% → "narrowly missed statistical significance for its primary end point" of total HF hospitalizations and CV death. [@Solomon2019]

    -   Primary endpoint was reduced by 13% in favor of sacubitril/valsartan (hazard ratio, 0.87; 95% confidence interval, 0.75-1.01; p = .059).

    -   See "Making the Case for an Expanded Indication for Sacubitril/Valsartan in Heart Failure" [@Solomon2021]

## Initiation of Entresto

:::{.callout-warning}
"Because sacubitril/valsartan therapy affects several biomarkers and specifically inhibits the breakdown of brain natriuretic peptide (BNP), BNP will be elevated in patients taking this drug. Therefore, BNP will not be a reliable marker of heart failure exacerbations in these patients. NT-pro-BNP is not a substrate for neprilysin, and therefore not affected by sacubitril. As such, NT-pro-BNP should be utilized in patients on sacubitril/valsartan when a heart-failure exacerbation is suspected." [Source](https://www.ncbi.nlm.nih.gov/books/NBK507904/)
:::

- Patients must be able to tolerate an ACEI or an ARB prior to being started on sacubitril/valsartan.
- **Washout period**: stop ACEi 24-36 hrs prior to initiation
  - The washout period is *not* needed when switching from an ARB to sacubitril/valsartan.
- Lower/stop other diuretics upon initiation (because of sacubitril's diuretic effect)
- Start at lowest dose and titrate up every 2-4 wks
- Consider initiation during hospitalization for ADHF \\\[PIONEER-HF trial\\\]
- Continue outpatient ARNI/ARB/ACEi/aldosterone antagonist and beta blocker during diuresis if blood pressure allows. [@Tran2018]


## Recommended Dosing

- [Source](https://www.ncbi.nlm.nih.gov/books/NBK507904/)
-   Patients on low-dose ACEI or ARB or not previously on ACEI or ARB start with sacubitril 24 mg/valsartan 26 mg BID. Double the dose every 2 to 4 weeks as tolerated, up to Sacubitril 97 mg/valsartan 103 mg BID.
-   Patients on moderate to high dose of ACEI or ARB start with sacubitril 49 mg/valsartan 51 mg twice per day. Double the dose every 2 to 4 weeks as tolerated, up to sacubitril 97 mg/valsartan 103 mg orally twice per day.
-   Patients with eGFR less than 30 or moderate hepatic impairment (Child-Pugh class B) should start with sacubitril 24 mg/valsartan 26 mg twice per day.
- Sacubitril/valsartan is *not* recommended in severe hepatic impairment (Child-Pugh class C).
    




