# Hypertrophic cardiomyopathy

``` text
# Hypertrophic cardiomyopathy
- Obtain family history with at least 3 generation tree (2020 Guidelines)
- Rhythm surveillance:
  - EKG + 24-48 hr ambulatory ECG monitoring
  - Surveillance ECG recommended every 1-2 years
- Pharmacotherapy:
  - non-vasodilating BBs (first-line)
  - Verapamil > dilt
    - Contraindications: hypOtension, severe dyspnea at rest, children <6 weeks old, and for resting gradients over 100 mm Hg
  - If refractory to BB, CCBs -> Disopyramide (negative inotropic)
- Devices
  - Primary prevention: if risk factors (e.g. fam hx SCD, hypOtensive w/ exercise)
    - Class IIa rec for pts w/ massive LVH ≥30 mm, hx of suspected cardiac syncope, LV apical aneurysm, EF <50%, or family hx of SCD due to HCM
  - Secondary prevention: survivors of cardiac arrest/VT
    - single-chamber transvenous or subQ ICD (Class I)
- Avoid medications that decrease preload (e.g. diuretics, nitro), decrease afterload (e.g. ACEi/ARB, amlodipine), increase contractility (e.g. digoxin, dobutamine, milrinone)
- Imaging:
  - Echo
    - If LVOT gradient < 50 mmHg, then provocative testing should be performed
    - If Sx w/o provoked gradients -> get exercise echo
    - If ASx, get surveillance echo q1-2 yrs to assess ∆ in hypertrophy, obstruction, cardiac function
  - Cardiac MRI
    - especially if echo is inconclusive or suspect alternative Dx (e.g. infiltrative/storage disease)
    - useful for SCD risk stratification and selection/planning for septal reduction therapy
- Offer genetic testing (shared decision making) and allow for family screening
  - First degree relatives:
    - initial eval: screen w/ ECG, TTE
    - follow-up: every 1-2 years in adolescents, 3-5 years in adults *or* if clinical status changes
- If systolic dysfunction (EF < 50%) -> CAD r/o  and start GDMT for HFrEF
- If pregnant
  - BBs should be continued with monitoring of fetal growth and care should be coordinated between cardiology and obstetrics.
  - If needs AC for AFib or other reason, LMWH or warfarin (if max dose < 5 mg daily)
```

-   AHA/ACC 2020 Guidelines [@ommen2020]

-   LVOT obstruction is caused by abnormal systolic anterior motion (SAM) of the anterior leaflet of the MV toward a hypertrophied interventricular septum

-   Most common Sx:

    -   dyspnea (90%)
    -   angina
    -   fatigue
    -   palpitations
    -   syncope/pre-syncope (See @sec-syncope)

-   Sx of advanced heart failure, e.g. orthopnea, PND, edema, are uncommon.

- ECG findings classic for HOCM are:
  - Ventricular hypertrophy
  - Repolarization abnormalities in those leads with the tallest R waves
  - Narrow, deep Q waves, of uncertain etiology, most often in the inferior and lateral leads

-   *All* pts w/ HOCM and AFib should be on anticoagulation (regardless of CHADS-VASc)

    -   DOACs are first-line; warfarin is second-line

-   Risk factors for sudden cardiac death (SCD) in patients w/ known HOCM:

    -   septal thickness \> 30 mm
    -   hx of syncope
    -   fam hx of SCD in 1st degree relative
    -   NSVT on Holter
    -   failure to augment SBP w/ ETT (\<10 mmHg ↑ at peak exercise)

-   Surgical options for HCM management:

    -   septal myectomy (Morrow procedure)
    -   alcohol septal ablation (ASA)

-   Septal myectomy (Morrow procedure) is the gold standard intervention for mgmt of Hypetrophic cardiomyopathy (HCM) pts w/ *severe* Sx refractory to meds
