# MINOCA


-   Myocardial infarction with non-obstructive coronary arteries (MINOCA)
- MINOCA is defined as acute MI associated with a rise and fall of troponin on serial assessment with at least 1 value above the 99th percentile upper reference limit, combined with clinical evidence of infarction, nonobstructive coronary arteries on angiography, and no alternative etiology to explain the diagnosis. 
-   Affects ♀ \> ♂
  - Women are approximately 5 times more likely than men to have MINOCA (14.9%vs 3.5%), and patients who are “non-White” are approximately 1.5 times more likely than patients who are White to have MINOCA (14.9% vs 10.0%).
- MINOCA is present in approximately 5% to 6% of patients with MI.
-   Diagnostic criteria:
    -   acute myocardial infarction, i.e. EKG ∆, ↑ trops, CP
    -   non-obstructive coronary aa. on cath
        -   defined as stenosis \< 50% in any potential infarct-related epicardial artery
    -   no clinically overt alternative explanation, i.e. need to r/o other possible etiologies - coronary-mediated ischemia or myocardial injury

+-------------------+------------------------------------------+-------------------------------------------+
| General etiology  | Diagnosis                                | Dx work-up                                |
+===================+==========================================+===========================================+
| Ischemia          | Coronary thrombosis and rapid clot lysis | Cath with IVUS                            |
+-------------------+------------------------------------------+-------------------------------------------+
| Ischemia          | Micro and macro emboli                   | TTE, TEE                                  |
+-------------------+------------------------------------------+-------------------------------------------+
| Ischemia          | Coronary vasospasm                       | Hx (rest pain, recurrent episodic)\       |
|                   |                                          | UDS\                                      |
|                   |                                          | Acetylcholine provocation test            |
+-------------------+------------------------------------------+-------------------------------------------+
| Ischemia          | Coagulopathy                             | Thrombophilia screen (target based on hx) |
+-------------------+------------------------------------------+-------------------------------------------+
| Ischemia          | Vasculitis                               | ESR, CRP                                  |
+-------------------+------------------------------------------+-------------------------------------------+
| Ischemia          | Coronary micovascular dysfunction        | PET\                                      |
|                   |                                          | Coronary flow reserve                     |
+-------------------+------------------------------------------+-------------------------------------------+
| Myocardial injury | Myocarditis                              | ESR, CRP\                                 |
|                   |                                          | Cardiac MRI                               |
+-------------------+------------------------------------------+-------------------------------------------+
| Myocardial injury | PE (Right ❤️ strain)                     | CTA                                       |
+-------------------+------------------------------------------+-------------------------------------------+
| Myocardial injury | Cardiomyopathy (inc. Takotsubo)          | Echo\                                     |
|                   |                                          | Cardiac MRI                               |
+-------------------+------------------------------------------+-------------------------------------------+

: Conditions to exclude for Dx of MINOCA (Pasupathy et al., 2015 via BrighamChiefs, Aug 19, 2020)
