# Pericarditis

```text
Pericarditis
- EKG
- Labs
    - BMP
    - Trop - usually +, so not helpful from distinguishing other causes of CP
    - TB - Quantiferon
    - ANA
    - BC
- Imaging
    - Echo
    - CXR
- Treatment
    - NSAIDs
    - Colchicine - shown to improve Tx response and decrease disease recurrence
    - Predisone if refractory and other diseases are ruled out
- Pericardiocentesis if tamponade
```

-   Typical illness script
    -   Hx: young adults, with 1 week of viral symptoms and chest pain that improves with leaning forward
    -   Physical exam: 3-part friction rub
    -   ECG: ST elevations and PR depressions in *all* leads
    -   EKG
        -   *most commonly* widespread ST elevations and PR depressions
        -   Differentiate from acute MI. Differentiating factors:
            -   ST elevation
                -   Pericarditis: usually diffuse
                -   MI: usually localized to leads associated with the area of ischemia/infarction
            -   PR depression is very uncommon in acute MI
            -   Q waves are not present with pericarditis
    -   DDx:
        -   Viral pericarditis; primarily caused by coxsackievirus, echovirus, and adenovirus
        -   Other infectious, e.g. TB, HIV
        -   Post-MI and postcardiac surgery
        -   Rheum: includes SLE and RA
        -   Meds: includes procainamide and hydralazine
        -   Malignancy that has metastasized to the pericardium
        -   Chest irradiation
        -   Uremia
    -   Complications:
        -   Pleural effusions
        -   ⚠️ Cardiac tamponad
        
:::{.callout-warning}
Pts w/ **uremic pericarditis** often do *not* present with 'classic' EKG features
:::
