# Mechanical/Bioprosthetic Heart Valves

+-----------+------------------------------------------------------------------+-------------------------------------------------------------+----------------------------------------------------------------------------------------------+
|           | Mechanical Valve                                                 | Bioprosthetic Valve                                         | Transcatheter Aortic Valve (TAVR)                                                            |
+===========+==================================================================+=============================================================+==============================================================================================+
| Material  | Plastic                                                          | Bovine, Equine, or Porcine pericardium or aortic valves     | Porcine or Bovine pericardium                                                                |
+-----------+------------------------------------------------------------------+-------------------------------------------------------------+----------------------------------------------------------------------------------------------+
| Lifespan  | 25-30 years                                                      | 10-15 years                                                 | 91% of pts at 5-10 yrs have functioning valves                                               |
+-----------+------------------------------------------------------------------+-------------------------------------------------------------+----------------------------------------------------------------------------------------------+
| Results   | Durability<br />↓ incidence of ppm<br />↓ risk paravalvular leak | No AC<br />↓ incidence of ppm<br />↓ risk paravalvular leak | No AC<br />Less invasive procedure<br />↓ mortality<br />↓ AKI<br />↓ bleeding<br />↓ stroke |
+-----------+------------------------------------------------------------------+-------------------------------------------------------------+----------------------------------------------------------------------------------------------+
| Drawbacks | AC needed<br />hemolytic anemia<br />invasive procedure          | Shorter lifespan<br />Invasive procedure                    | Shorter lifespan                                                                             |
+-----------+------------------------------------------------------------------+-------------------------------------------------------------+----------------------------------------------------------------------------------------------+

## Anticoagulation

- **Mechanical** heart valves that should be on warfarin with an INR goal 2.5-3.5
    -   mitral valve replacement
    -   aortic valve replacement w/ risk factors
    -   1st 3 months after aortic valve replacement (weak rec)
